### ISSUE TITLE
Making a longer em-dash

### ISSUE THREAD

**Issue by pretentiousUsername** [adobe-fonts/source-serif#113]
Howdy everyone!

I know this is probably a bit petty, but I think that Source Serif needs a better em-dash—and yes, I'm mostly saying this because I overuse dashes.

In most typefaces I like, such as Charter—which Source Serif quite obviously takes a lot of inspiration from—the dashes are sized in proportion to hyphens such that an en-dash is two hyphens long, and an em-dash is two en-dashes. Changing the dash lengths in Source Serif would boost readability, and allow for greater typographic flexibility.

**Comment by frankrolf** [comment]
Hello @pretentiousUsername; this is an interesting issue, and it’s not something I am likely to change – simply because it will affect a lot of already-existing text already set in Source Serif.

Nevertheless, some explanation/clarification for you:
* Charter and Source Serif share stylistic elements, this is due to the shared historical source material. Taking direct inspiration from Charter wouldn’t be very useful for Source Serif, because the goals of the families are quite different.
* Charter is a relatively old digital design, in which en- and em-dashes are simply 500 and 1000 units wide respectively Also, those dashes don’t have any sidebearings.
* I don’t think this makes a lot of sense today, therefore the dashes in Source Serif are sized optically, rather than mathematically.
* Just for humoring you, here are some comparisons between SS and Charter (both Regular styles):

| M | LSB | width | RSB | 
| --- | --- | --- | --- |
| Charter | 30 | 866 | 32 |
| Source Serif | 39 | 902 | 45 |


| hyphen | LSB | width | RSB | 
| --- | --- | --- | --- |
| Charter | 47 | 319 | 47 |
| Source Serif | 40 | 312 | 40 |


| endash | LSB | width | RSB | 
| --- | --- | --- | --- |
| Charter | 0 | 500 | 0 |
| Source Serif | 40 | 512 | 40 |


| emdash | LSB | width | RSB | 
| --- | --- | --- | --- |
| Charter | 0 | 1000 | 0 |
| Source Serif | 40 | 812 | 40 |


I don’t know how changing the dash lengths would ❝boost readability, and allow for greater typographic flexibility❞, therefore I am closing this issue with a big `[citation needed]`

**Comment by pretentiousUsername** [comment]
I probably should have put an "in my opinion" before saying that a longer dash would boost readability.

**Comment by frankrolf** [comment]
No worries, I understood. Thank you for understanding my position as well :-)
