### ISSUE TITLE
Missing a non-breaking hyphen

### ISSUE THREAD

**Issue by daveredfern** [adobe-fonts/source-serif#73]
Hi everyone,

Thanks for creating this lovely font. I am using a subfont script for my website so I ship the characters I use. I noticed that script is flagging that a non-breaking hyphen is missing from the fonts.

If it is, could you add to your to-do list when you have chance, please?

Thanks,

Dave.

**Comment by frankrolf** [comment]
I see this bug is already closed – if you still need to support the code point U+2011 NON-BREAKING HYPHEN, it could be added quite easily by amending this line: 
https://github.com/adobe-fonts/source-serif-pro/blob/main/Roman/GlyphOrderAndAliasDB#L498

The hyphen already is triple-encoded, to support
- U+002D HYPHEN-MINUS
- U+00AD SOFT HYPHEN
- U+2010 HYPHEN

Just curious – which environment are you missing the non-breaking hyphen in?
Thanks.

**Comment by frankrolf** [comment]
I re-read the original issue and you indeed mentioned where you find that to be an issue. Can you point me to the subsetter you are using? Perhaps the rules within are a bit too strict.

**Comment by daveredfern** [comment]
Thanks @frankrolf. I did close the issue realizing that it might not be related to your font but the subsetter. I’m using it with [Netlify Plugin Subset](https://github.com/Munter/netlify-plugin-subfont) that from [my understanding](https://github.com/Munter/netlify-plugin-subfont/issues/55#issuecomment-649477132) uses [subfont]( https://github.com/Munter/subfont).

Cheers!

**Comment by daveredfern** [comment]
@frankrolf just noticed that I was using the non-breaking hyphen from [Toptal’s page](https://www.toptal.com/designers/htmlarrows/punctuation/non-breaking-hyphen/) that has the unicode U+02011.

That probably explains the issue.

**Comment by Munter** [comment]
The subsetter in subfont is pyton fonttools `pyftsubset` with a configuration that can be inferred from these lines of code: https://github.com/Munter/subfont/blob/de6a482f31075245ed957aa8057a24e31addd612/lib/subsetLocalFont.js#L47-L60

**Comment by quasicomputational** [comment]
I'd also appreciate U+2011 being encoded, please. The non-breaking-ness makes it a bit annoying to substitute. I've also verified that it's not present even in the original, non-subsetted WOFF2 files (or, at least, if it is, then Firefox isn't using it for some reason).

**Comment by frankrolf** [comment]
The non-breaking hyphen is present in Source Serif, and has been encoded since Jun 28, 2018.
(I was curious so I checked the commit history – the commit that added it is `c207f89035ab35fdc7f0e90df5781e2fd1730cc7`)

This means it should be found in version 2.007 and upward.
Please check the version you’re using, and please report back if you can’t the non-breaking hyphen even in newer versions of the fonts.

Thanks!

**Comment by quasicomputational** [comment]
Huh - looks like it's a Firefox bug where it won't use a non-breaking hyphen from a webfont, or something like that! Thanks for the patience.

**Comment by quasicomputational** [comment]
No, sorry, further investigation has revealed that this is a Source Serif Pro problem: that commit doesn't add U+2011, which is the non-breaking hyphen and the codepoint I would like to see mapped. (The *does* had U+2010, which is a normal breaking hyphen, though.)

I was misled by Chromium having a clever fallback and apparently working - it looks like it shows U+2010 or U+002D if U+2011 isn't present, which makes sense.

**Comment by frankrolf** [comment]
Got it now, sorry.
Will add the code point – the non-breaking hyphen will be in the next release!
