### ISSUE TITLE
Hinting for Windows

### ISSUE THREAD

**Issue by Daymarius** [adobe-fonts/source-serif#93]
Need hinting like in 2.000 version for Windows.

**Comment by frankrolf** [comment]
Please provide more information.

**Comment by Daymarius** [comment]
Hinted:
![Screenshot_119](https://user-images.githubusercontent.com/18142611/112877694-bee15300-90cf-11eb-89b6-d40743c12fbd.png)

Not hintned:
![Screenshot_120](https://user-images.githubusercontent.com/18142611/112877720-c56fca80-90cf-11eb-8665-7d09f0b7325d.png)

**Comment by frankrolf** [comment]
I was thinking of information along the lines of

- version of Windows used
- OTF or TTF fonts used
- specific use case for TT-hinted fonts (assuming this to be the nature of the bug).

The OTF fonts are hinted – FYI.

**Comment by Daymarius** [comment]
OTF is not good for text in Windows, CFF rendering in Windows not as good as in Mac and Linux, it looks like a font without hints but is thicker.
![Screenshot_118](https://user-images.githubusercontent.com/18142611/112882084-2cdc4900-90d5-11eb-9860-00ebc86b7bdb.png)

**Comment by Daymarius** [comment]
TTF Hinted:
![Screenshot_121](https://user-images.githubusercontent.com/18142611/112883554-1c2cd280-90d7-11eb-9459-7b15b6cbb655.png)
CFF:
![Screenshot_122](https://user-images.githubusercontent.com/18142611/112883632-35ce1a00-90d7-11eb-8dff-0bf077eafc48.png)

**Comment by Daymarius** [comment]
In web (Google Chrome)

TTF Hinted:
![Screenshot_123](https://user-images.githubusercontent.com/18142611/112885587-9bbba100-90d9-11eb-8af0-18e61844f24d.png)

TTF Not Hinted:
![Screenshot_124](https://user-images.githubusercontent.com/18142611/112885616-a413dc00-90d9-11eb-8cb7-f1b09f55475e.png)

OTF:
![Screenshot_125](https://user-images.githubusercontent.com/18142611/112885634-a83ff980-90d9-11eb-803a-3685633c2bcb.png)

**Comment by frankrolf** [comment]
These screenshots only allow for subjective comparisons. 
I am still hoping to hear answers to
- version of Windows used
- specific use case for TT-hinted fonts

**Comment by Daymarius** [comment]
Windows 10
Have you used windows?

**Comment by frankrolf** [comment]
I have used Windows, yes. Windows is part of our regular testing cycle. But that’s off the point.

This issue is an example of confirmation bias. It is true that the looks of the typeface have changed through omitted TT hinting. But have they changed for the worse? No.
None of the screenshots provided (except one) prove that the hinted TTF looks better than the unhinted variant – this is why I say you provide a “subjective comparison”.
If anything, they demonstrate how well the unhinted font works, which is a testament to Windows’ improvements in rasterization.

The only environment in which the hinted TTFs objectively look better is Notepad – presumably because the rasterization within is as ancient as the application itself.

It’s been years since the TT hints have been dropped from the family. This fact is not the product of a frivolous decision, but a conscious change in strategy which frees up significant amounts of time better spent on expanding the fonts in terms of language coverage.
